version: '3.8'

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql-prod/data
      - /var/run/experts:/var/run/postgresql
    env_file:
      - ./.db.env
    expose:
      - 5432
    restart: unless-stopped

  backups:
    container_name: backup
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    volumes:
      - ../backup:/backups
    links:
      - db:db
    depends_on:
      - db
    env_file:
       ./.backups.env

  web:
    image: "${WEB_IMAGE}"
    volumes:
      - static_volume:/home/app/web/static-root
      - media_volume:/home/app/web/media
      - /var/run/experts:/var/run/gunicorn
    command: "gunicorn root.wsgi:application \
    --workers 2 --user=root --group root --bind=unix:/var/run/gunicorn/gunicorn.sock --log-file=-"
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/static-root
      - media_volume:/home/app/web/media
      - /var/run/experts:/var/run/experts
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
