# Generated by Django 3.1.6 on 2021-02-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='book')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='joined time')),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Experts',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('_type', models.CharField(choices=[('илимий', 'илимий'), ('илимий-педагогикалык', 'илимий-педагогикалык'), ('антидискриминациялык жана гендердик', 'антидискриминациялык жана гендердик')], max_length=255, verbose_name='Type')),
                ('document', models.TextField(verbose_name='document')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.book')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
                'ordering': ('-created',),
            },
        ),
    ]
