# Generated by Django 3.1.6 on 2021-02-06 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='okuu_kitep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history1', to=settings.AUTH_USER_MODEL, verbose_name='commission one'),
        ),
        migrations.AddField(
            model_name='history',
            name='sector_knigi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history2', to=settings.AUTH_USER_MODEL, verbose_name='commission two'),
        ),
        migrations.AddField(
            model_name='history',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.expert', verbose_name='Winner'),
        ),
        migrations.AddField(
            model_name='expert',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.book'),
        ),
    ]
