# Generated by Django 3.2.9 on 2021-12-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='expert',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.book', verbose_name='book'),
        ),
    ]
