# Generated by Django 3.1.6 on 2021-02-07 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_auto_20210206_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='okuu_kitep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history1', to=settings.AUTH_USER_MODEL, verbose_name='Okuu Kitep'),
        ),
        migrations.AlterField(
            model_name='history',
            name='sector_knigi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history2', to=settings.AUTH_USER_MODEL, verbose_name='Sector Knigi'),
        ),
    ]
