name: Production CI CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILDER_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/builder
  WEB_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/web
  NGINX_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/nginx

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
      - name: Add environment variables to .env
        run: |
          echo DEBUG=${DEBUG} >> ./root/.env
          echo DATABASE=${{ env.DATABASE }} >> ./root/.env
          echo SECRET_KEY=${{ env.SECRET_KEY }} >> ./root/.env
          echo ALLOWED_HOSTS=${{ env.ALLOWED_HOSTS }} >> ./root/.env
          echo DB_NAME=${{ env.env }} >> ./root/.env
          echo DB_USER=${{ env.DB_USER }} >> ./root/.env
          echo DB_PWD=${{ env.DB_PWD }} >> ./root/.env
          echo DB_HOST=${{ env.DB_HOST }} >> ./root/.env
          echo DB_SOCK=${{ env.DB_SOCK }} >> ./root/.env
          echo DB_PORT=${{ env.DB_PORT }} >> ./root/.env
          echo EMAIL_HOST_PWD=${{ env.EMAIL_HOST_PWD }} >> ./root/.env
          echo EMAIL_HOST=${{ env.EMAIL_HOST }} >> ./root/.env
          echo EMAIL_PORT=${{ env.EMAIL_PORT }} >> ./root/.env
          echo EMAIL_HOST_USER=${{ env.EMAIL_HOST_USER }} >> ./root/.env
      - name: Set environment variables
        run: |
          echo "BUILDER_IMAGE=$(echo ${{ env.BUILDER_IMAGE }} )" >> $GITHUB_ENV
          echo "WEB_IMAGE=$(echo ${{ env.WEB_IMAGE }} )" >> $GITHUB_ENV
          echo "NGINX_IMAGE=$(echo ${{ env.NGINX_IMAGE }} )" >> $GITHUB_ENV
      - name: Login to Github Packages
        run: echo ${PERSONAL_ACCESS_TOKEN} | docker login ghcr.io -u ${{ secrets.NAMESPACE}} --password-stdin
        env:
          PERSONAL_ACCESS_TOKEN: ${{ env.PERSONAL_ACCESS_TOKEN }}
      - name: Pull images
        run: |
          docker pull ${{ env.BUILDER_IMAGE }} || true
          docker pull ${{ env.WEB_IMAGE }} || true
          docker pull ${{ env.NGINX_IMAGE }} || true
      - name: Build images
        run: |
          docker-compose -f docker-compose.ci.yml build
      - name: Push images
        run: |
          docker push ${{ env.BUILDER_IMAGE }}
          docker push ${{ env.WEB_IMAGE }}
          docker push ${{ env.NGINX_IMAGE }}

  deploy:
    name: Deploy to Host
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
      - name: Add environment variables to .env
        run: |
          echo WEB_IMAGE=${{ env.WEB_IMAGE }} >> ./.env
          echo NGINX_IMAGE=${{ env.NGINX_IMAGE }} >> ./.env
          echo NAMESPACE=${{ env.NAMESPACE }} >> ./.env
          echo PERSONAL_ACCESS_TOKEN=${{ env.PERSONAL_ACCESS_TOKEN }} >> ./.env
          echo POSTGRES_USER=${{ env.DB_USER }} >> ./.db.env
          echo POSTGRES_PASSWORD=${{ env.DB_PWD }} >> ./.db.env
          echo POSTGRES_DB=${{ env.DB_NAME }} >> ./.db.env
          echo POSTGRES_HOST=${{ env.DB_HOST }} >> ./.backups.env
          echo POSTGRES_DB=${{ env.DB_NAME }} >> ./.backups.env
          echo POSTGRES_USER=${{ env.DB_USER }} >> ./.backups.env
          echo POSTGRES_PASSWORD=${{ env.DB_PWD }} >> ./.backups.env
          echo POSTGRES_EXTRA_OPTS=${{ env.POSTGRES_EXTRA_OPTS }} >> ./.backups.env
          echo SCHEDULE=${{ env.SCHEDULE }} >> ./.backups.env
          echo BACKUP_KEEP_DAYS=${{ env.BACKUP_KEEP_DAYS }} >> ./.backups.env
          echo BACKUP_KEEP_WEEKS=${{ env.BACKUP_KEEP_WEEKS }} >> ./.backups.env
          echo BACKUP_KEEP_MONTHS=${{ env.BACKUP_KEEP_MONTHS }} >> ./.backups.env
          echo HEALTHCHECK_PORT=${{ env.HEALTHCHECK_PORT }} >> ./.backups.env
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ env.PRIVATE_KEY }}"
      - name: Build and deploy images on Host
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp -o StrictHostKeyChecking=no -P {{ env.HOST_PORT }} "./.env" "./.db.env" "./.backups.env" "./docker-compose.yml" root@${{ env.HOST_IP_ADDRESS }}:/root/kitep
          ssh -o StrictHostKeyChecking=no root@${{ env.HOST_IP_ADDRESS }} -p {{ env.HOST_PORT }} << 'ENDSSH'
            cd /root/kitep
            source ./.env
            docker login ghcr.io -u $NAMESPACE -p $PERSONAL_ACCESS_TOKEN
            docker pull $WEB_IMAGE
            docker pull $NGINX_IMAGE
            docker pull $REDIS_IMAGE
            docker-compose -f docker-compose.yml up -d
            docker image prune -f
            docker-compose exec -d web gunicorn root.wsgi:application --name kitep --workers 2 --user=root --group root --bind=unix:/var/run/gunicorn/gunicorn.sock --log-level=debug --log-file=-
          ENDSSH
