name: Production CI CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILDER_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/builder
  WEB_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/web
  NGINX_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/nginx
  REDIS_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/redis

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
      - name: Add environment variables to .env
        run: |
          echo DEBUG=${{ secrets.DEBUG }} >> ./root/.env
          echo DATABASE=${{ secrets.DATABASE }} >> ./root/.env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> ./root/.env
          echo LANGUAGE_CODE=${{ secrets.LANGUAGE_CODE }} >> ./root/.env
          echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> ./root/.env
          echo DB_NAME=${{ secrets.DB_NAME }} >> ./root/.env
          echo DB_USER=${{ secrets.DB_USER }} >> ./root/.env
          echo DB_PWD=${{ secrets.DB_PWD }} >> ./root/.env
          echo DB_HOST=${{ secrets.DB_HOST }} >> ./root/.env
          echo DB_SOCK=${{ secrets.DB_SOCK }} >> ./root/.env
          echo DB_PORT=${{ secrets.DB_PORT }} >> ./root/.env
          echo EMAIL_HOST_PWD=${{ secrets.EMAIL_HOST_PWD }} >> ./root/.env
          echo EMAIL_HOST=${{ secrets.EMAIL_HOST }} >> ./root/.env
          echo EMAIL_PORT=${{ secrets.EMAIL_PORT }} >> ./root/.env
          echo EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }} >> ./root/.env
          echo CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }} >> ./root/.env
      - name: Set environment variables
        run: |
          echo "BUILDER_IMAGE=$(echo ${{ env.BUILDER_IMAGE }} )" >> $GITHUB_ENV
          echo "WEB_IMAGE=$(echo ${{ env.WEB_IMAGE }} )" >> $GITHUB_ENV
          echo "NGINX_IMAGE=$(echo ${{ env.NGINX_IMAGE }} )" >> $GITHUB_ENV
          echo "REDIS_IMAGE=$(echo ${{ env.REDIS_IMAGE }} )" >> $GITHUB_ENV
      - name: Login to Github Packages
        run: echo ${PERSONAL_ACCESS_TOKEN} | docker login ghcr.io -u ${{ secrets.NAMESPACE}} --password-stdin
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Pull images
        run: |
          docker pull ${{ env.BUILDER_IMAGE }} || true
          docker pull ${{ env.WEB_IMAGE }} || true
          docker pull ${{ env.NGINX_IMAGE }} || true
          docker pull ${{ env.REDIS_IMAGE }} || true
      - name: Build images
        run: |
          docker compose -f docker-compose.ci.yml build
      - name: Push images
        run: |
          docker push ${{ env.BUILDER_IMAGE }}
          docker push ${{ env.WEB_IMAGE }}
          docker push ${{ env.NGINX_IMAGE }}
          docker push ${{ env.REDIS_IMAGE }}

  deploy:
    name: Deploy to Host
    runs-on: ubuntu-latest
    environment: prod
    needs: build
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
      - name: Add environment variables to .env
        run: |
          echo WEB_IMAGE=${{ env.WEB_IMAGE }} >> ./.env
          echo NGINX_IMAGE=${{ env.NGINX_IMAGE }} >> ./.env
          echo REDIS_IMAGE=${{ env.REDIS_IMAGE }} >> ./.env
          echo NAMESPACE=${{ secrets.NAMESPACE }} >> ./.env
          echo PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> ./.env
          echo POSTGRES_USER=${{ secrets.DB_USER }} >> ./.db.env
          echo POSTGRES_PASSWORD=${{ secrets.DB_PWD }} >> ./.db.env
          echo POSTGRES_DB=${{ secrets.DB_NAME }} >> ./.db.env
          echo POSTGRES_HOST=${{ secrets.DB_HOST }} >> ./.backups.env
          echo POSTGRES_DB=${{ secrets.DB_NAME }} >> ./.backups.env
          echo POSTGRES_USER=${{ secrets.DB_USER }} >> ./.backups.env
          echo POSTGRES_PASSWORD=${{ secrets.DB_PWD }} >> ./.backups.env
          echo POSTGRES_EXTRA_OPTS=${{ secrets.POSTGRES_EXTRA_OPTS }} >> ./.backups.env
          echo SCHEDULE=${{ secrets.SCHEDULE }} >> ./.backups.env
          echo BACKUP_KEEP_DAYS=${{ secrets.BACKUP_KEEP_DAYS }} >> ./.backups.env
          echo BACKUP_KEEP_WEEKS=${{ secrets.BACKUP_KEEP_WEEKS }} >> ./.backups.env
          echo BACKUP_KEEP_MONTHS=${{ secrets.BACKUP_KEEP_MONTHS }} >> ./.backups.env
          echo HEALTHCHECK_PORT=${{ secrets.HEALTHCHECK_PORT }} >> ./.backups.env
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
      - name: Copy files
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            scp -o StrictHostKeyChecking=no -P 2021 "./.env" "./.db.env" "./.backups.env" "./docker-compose.yml" kitep@85.113.15.230:/root/experts
      # - name: build
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   run: |
      #     ssh -o StrictHostKeyChecking=no kitep@${{ secrets.HOST_IP_ADDRESS }} -p ${{ secrets.HOST_PORT }} << 'ENDSSH'
      #       cd /root/experts
      #     ENDSSH
      - name: Build and deploy images on Host
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -o StrictHostKeyChecking=no kitep@${{ secrets.HOST_IP_ADDRESS }} -p ${{ secrets.HOST_PORT }} << 'ENDSSH'
            cd /root/experts
            source ./.env
            docker login ghcr.io -u $NAMESPACE -p $PERSONAL_ACCESS_TOKEN
            docker pull $WEB_IMAGE
            docker pull $NGINX_IMAGE
            docker pull $REDIS_IMAGE
            docker-compose -f docker-compose.yml up -d
            docker image prune -f
            docker-compose exec -d web gunicorn root.wsgi:application --name web --workers 2 --user=root --group root --bind=unix:/var/run/gunicorn/gunicorn.sock --log-level=debug --log-file=-
            docker-compose exec -d web celery -A root worker -l info
          ENDSSH
